// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientInfo {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoipServerEvent {
    #[prost(enumeration = "voip_server_event::EventType", tag = "1")]
    pub event_type: i32,
    #[prost(string, tag = "2")]
    pub current_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(oneof = "voip_server_event::EventPayload", tags = "4, 5, 6, 7, 8")]
    pub event_payload: ::core::option::Option<voip_server_event::EventPayload>,
}
/// Nested message and enum types in `VoipServerEvent`.
pub mod voip_server_event {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum EventType {
        Ping = 0,
        MemberJoined = 1,
        MemberLeft = 2,
        MemberMuted = 3,
        MemberUnmuted = 4,
        MemberSpeaking = 5,
        CurrentUserLeft = 6,
    }
    impl EventType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Ping => "event_type_ping",
                Self::MemberJoined => "event_type_member_joined",
                Self::MemberLeft => "event_type_member_left",
                Self::MemberMuted => "event_type_member_muted",
                Self::MemberUnmuted => "event_type_member_unmuted",
                Self::MemberSpeaking => "event_type_member_speaking",
                Self::CurrentUserLeft => "event_type_current_user_left",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "event_type_ping" => Some(Self::Ping),
                "event_type_member_joined" => Some(Self::MemberJoined),
                "event_type_member_left" => Some(Self::MemberLeft),
                "event_type_member_muted" => Some(Self::MemberMuted),
                "event_type_member_unmuted" => Some(Self::MemberUnmuted),
                "event_type_member_speaking" => Some(Self::MemberSpeaking),
                "event_type_current_user_left" => Some(Self::CurrentUserLeft),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum EventPayload {
        #[prost(message, tag = "4")]
        MemberJoined(super::MemberJoined),
        #[prost(message, tag = "5")]
        MemberLeft(super::MemberLeft),
        #[prost(message, tag = "6")]
        MemberMuted(super::MemberMuted),
        #[prost(message, tag = "7")]
        MemberUnmuted(super::MemberUnmuted),
        #[prost(message, tag = "8")]
        MemberSpeaking(super::MemberSpeaking),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberJoined {
    #[prost(string, tag = "1")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberLeft {
    #[prost(string, tag = "1")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberMuted {
    #[prost(string, tag = "1")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberUnmuted {
    #[prost(string, tag = "1")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberSpeaking {
    #[prost(string, tag = "1")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendDebugEventPayload {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dest_client_id: ::prost::alloc::string::String,
    #[prost(enumeration = "voip_server_event::EventType", tag = "3")]
    pub event_type: i32,
}
/// Room state snapshot (for initial registration or re-sync)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomState {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub member_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, bool", tag = "3")]
    pub muted_status: ::std::collections::HashMap<::prost::alloc::string::String, bool>,
    #[prost(map = "string, bool", tag = "4")]
    pub speaking_status: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        bool,
    >,
}
/// Generated client implementations.
pub mod voip_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct VoipServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl VoipServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> VoipServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> VoipServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            VoipServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Client registers with the server and starts receiving events.
        pub async fn join_room(
            &mut self,
            request: impl tonic::IntoRequest<super::ClientInfo>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::VoipServerEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/voip.VoipService/JoinRoom",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("voip.VoipService", "JoinRoom"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// We can connect to the server with another client and manually send debug
        /// events.
        pub async fn send_debug_event_to_client(
            &mut self,
            request: impl tonic::IntoRequest<super::SendDebugEventPayload>,
        ) -> std::result::Result<
            tonic::Response<super::VoipServerEvent>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/voip.VoipService/SendDebugEventToClient",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("voip.VoipService", "SendDebugEventToClient"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod voip_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with VoipServiceServer.
    #[async_trait]
    pub trait VoipService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the JoinRoom method.
        type JoinRoomStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::VoipServerEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Client registers with the server and starts receiving events.
        async fn join_room(
            &self,
            request: tonic::Request<super::ClientInfo>,
        ) -> std::result::Result<tonic::Response<Self::JoinRoomStream>, tonic::Status>;
        /// We can connect to the server with another client and manually send debug
        /// events.
        async fn send_debug_event_to_client(
            &self,
            request: tonic::Request<super::SendDebugEventPayload>,
        ) -> std::result::Result<tonic::Response<super::VoipServerEvent>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct VoipServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> VoipServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for VoipServiceServer<T>
    where
        T: VoipService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/voip.VoipService/JoinRoom" => {
                    #[allow(non_camel_case_types)]
                    struct JoinRoomSvc<T: VoipService>(pub Arc<T>);
                    impl<
                        T: VoipService,
                    > tonic::server::ServerStreamingService<super::ClientInfo>
                    for JoinRoomSvc<T> {
                        type Response = super::VoipServerEvent;
                        type ResponseStream = T::JoinRoomStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClientInfo>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as VoipService>::join_room(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = JoinRoomSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/voip.VoipService/SendDebugEventToClient" => {
                    #[allow(non_camel_case_types)]
                    struct SendDebugEventToClientSvc<T: VoipService>(pub Arc<T>);
                    impl<
                        T: VoipService,
                    > tonic::server::UnaryService<super::SendDebugEventPayload>
                    for SendDebugEventToClientSvc<T> {
                        type Response = super::VoipServerEvent;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendDebugEventPayload>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as VoipService>::send_debug_event_to_client(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendDebugEventToClientSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for VoipServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "voip.VoipService";
    impl<T> tonic::server::NamedService for VoipServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
